### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#1120]
### Problem

There's room for perf related improvements across the app and helm charts

### Solution

The below represent a few improvements to make performance goals and tracking easier to achieve and measure
- [x] Enable Kubernetes pod/container metrics in Grafana Agent.
- [x] Move metric time measurement to `finally` blocks
- [ ] ~#1714~
- [ ] ~#1715~
- [x] #1148
- [x] #1349 
- [x] Update `imagePullPolicy` to `IfNotPresent` instead of `Always` 
- [x] Add postman tests on k8s pod deployment

**Comment by Nana-EC** [comment]
Closing as most tickets are complete and remaining are no longer critical
