### ISSUE TITLE
[Design] Explore continuous automated RPC API schema verification

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#1475]
### Problem

The relay implements the Ethereum JSON RPC API 2.0 spec.
Occasionally changes are made externally or internally that may create differences and regressions in schema support.
The schema is clearly noted at execution-apis and can be found here https://github.com/ethereum/execution-apis

### Solution

Add a script, which scout the execution-apis repo for the tests (can explore https://github.com/octokit/rest.js). Create a list from the [folder names](https://github.com/ethereum/execution-apis/tree/main/tests) and go through each test, by sending a request to the relay using the schema described in the .io file. Add this to a workflow task, so that it should run at every pull request and report the result.

### Alternatives
Explore https://github.com/ethereum/hive/tree/master/simulators/ethereum/rpc-compat which does this, but for clients.

### Exploration
```[tasklist]
### Exploration tasks
- [x] eth_getBalance
- [x] eth_getBlockByHash
- [x] eth_getTransactionReceipt
- [x] eth_getTransactionByHash
- [x] eth_getTransactionByBlockHashAndIndex
- [x] eth_getTransactionByBlockNumberAndIndex
```

```[tasklist]
### Schema gap tasks
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1614
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1620
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1647
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1655
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1656
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1657
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1654
```
