### ISSUE TITLE
Refactor eth.spec.ts

### ISSUE THREAD

**Issue by Ivo-Yankov** [hashgraph/hedera-json-rpc-relay#1591]
### Problem

All unit tests for the `EthImpl` class are stored in a single file, which has reached 5000 lines of code. Any changes to this file triggers sonarcloud checks and result in multiple alerts due to poor code quality.

### Solution

- Split the file into dedicated spec files for every method.
- Try to reduce code duplication.

```[tasklist]
### Tasks
- [x] Refactor ETH_getBlockByHash spec
- [x] Refactor ETH_GetBlockByNumber spec
- [x] Refactor ETH_getBlockTransactionCountByNumber spec
- [x] Refactor ETH_getBlockTransactionCountByHash spec
- [x] Refactor ETH_getTransactionByBlockNumberAndIndex spec
- [x] Refactor ETH_getTransactionByBlockHashAndIndex spec
- [x] Refactor Block transaction count
- [x] Refactor ETH_getBalance spec
- [x] Refactor ETH_getCode spec
- [x] Refactor ETH_feeHistory spec
- [x] Refactor ETH_sendRawTransaction spec
- [x] Refactor ETH_gasPrice spec
- [x] Refactor ETH_estimateGas spec
- [x] Refactor ETH_call spec
- [x] Refactor ETH_getStorageAt spec
- [x] Refactor ETH_getTransactionCount spec
- [x] Refactor ETH_getTransactionReceipt spec
- [x] Refactor ETH_common spec
- [x] Refactor ETH_getTransactionByHash spec
- [x] Decreasing code duplications
```
