### ISSUE TITLE
Add Redis cache support

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-json-rpc-relay#1625]
### Problem

We currently have methods that need to share their cache between different relay instances. Otherwise they might not operate properly.

### Solution

Add Redis support in the relay and refactor cacheClient to support using either lru or redis, depending on method.
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1641
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1665
- [ ] https://github.com/hashgraph/hedera-local-node/issues/385
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1650
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1686
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1687
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1869
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1870
```

**Comment by Nana-EC** [comment]
@georgi-l95 can we close this or are the 2 remaining items still open?

**Comment by georgi-l95** [comment]
@Nana-EC Closing, as I think those are not needed. We can reopen, if needed.
