### ISSUE TITLE
JSON RPC Acceptance Test Plan

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [hashgraph/hedera-json-rpc-relay#188]
### Higher Priority
**eth_blockNumber**
- [ ] #217 

**eth_call** 
- [ ] #218

**getTransactionByHash**
- [x] #220

**eth_getTransactionReceipt**
- [ ] #219

### Low Priority

**eth_getBlockByHash**
- [x] #221

**eth_getBlockByNumber**
- [ ] #222

**eth_getBlockTransactionCountByNumber**
- [x] Add a negative test that queries the block transaction count for non-existing block number. The response must be asserted to:
```
{
  "result": null,
  "jsonrpc": "2.0",
  "id": 0
}
```
**eth_getBlockTransactionCountByHash**
- [x] Add a negative test that queries the block transaction count for non-existing block hash. The response must be asserted to:
```
{
  "result": null,
  "jsonrpc": "2.0",
  "id": 0
}
```
**eth_getUncleByBlockHashAndIndex**
- [x] Enhance the current test to pass arguments -> valid block hash and `0` index. Assert that the response is:
```
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": null
}
```
- [x] Add new test that uses **non existing** block hash and index `0`. Assert that the response is:
```
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": null
}
```
**eth_getUncleByBlockNumberAndIndex**
- [x] Enhance the current test to pass arguments -> valid block number and `0` index. Assert that the response is:
```
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": null
}
```
- [x] Add new test that uses **non existing** block number and index `0`. Assert that the response is:
```
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": null
}
```

**eth_feeHistory**
- [x] Add positive test
**eth_getCode**
- [ ] Deploy ERC20 and assert the code with eth_getCode
- [x] Execute getCode for non-contract address and assert the empty 0x response
```
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": "0x"
}
```

**eth_getTransactionByBlockNumberAndIndex**
- [x] Add negative test by providing invalid block number. Assert that the response is
```
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": null
}
```
- [x] Add negative test by providing invalid index. Assert that the response is
```
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": null
}
```
**eth_getTransactionByBlockHashAndIndex**
- [x] Add negative test by providing invalid block hash. Assert that the response is
```
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": null
}
```
- [x] Add negative test by providing invalid index. Assert that the response is
```
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": null
}
```
