### ISSUE TITLE
Returning the default gas value on a transaction that will fail when calling eth_estimateGas should not happen.

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#1965]
### Description

Failing transactions due to contract reverts are often accompanied by contract revert reasons that should be returned to the caller via eth_estimateGas.  In general this works, but there is a case on the local node in which an invalid response is returned from the web3 container causing the default gas to be returned in the relay and therefore not exposing the failed transaction and the contract revert reason.  This needs to be handled differently.

Also, due to the implementation history, a left over contract revert reason call with decoding of that contract revert reason, still exists in the eth_getTransactionByHash, and is called when DEV_MODE is set to true.  This needs to be deprecated.  Contract revert reasons need to be handled by eth_estimateGas.  

### Steps to reproduce

The ERC-4626 TokenVault test in the Hedera smart contracts repository contains tests that can reproduce this.  The simplest is the `Should fail if deposit is less than zero`.

On the local node the contract code gets deployed and is available to query, but when called returns an invalid response.  

### Hedera network

other

### Version

v0.37.0

### Operating system

macOS

```[tasklist]
### Sub Tasks
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1966
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7345
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/pull/1924
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1964
```
