### ISSUE TITLE
Enhance the `eth_subscribe` implementation to support `newHeads`

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#2117]
### Problem

The relay's `eth_subscribe` implementation currently does not support `newHeads`.

### Solution

Enhance the `eth_subscribe` implementation to support the `newHeads`

- [x] [Enhance](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2147) the webSocketServer to handle `newHeads`.
- [x] [Enhance](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2148) the `poller.ts` to handle the `newHeads` call.
- [x] [Add `wscat`/`WebSocket`](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2149) level tests to cover the `newHeads` call.
- [x] [Enhance](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2181) the webSocketServer to support necessary JSON RPC calls.
- [x] [Add](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2150) Hardhat tests to cover polling for new blocks.
- [x] [Add](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2151) ethers.js tests.
- [x] [Add ](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2168)metrics tracking polls.

**Comment by Nana-EC** [comment]
@ebadiere is there anything left over here or can this be closed?
