### ISSUE TITLE
Enhance the `webSocketServer.ts` to support the necessary JSON RPC methods.

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#2181]
### Problem

Polling for `newHeads` is great but JSON RPC calls within a subscription need to be handled.

### Solution

Implement support for the following in the `webSocketServer.ts`:

### Blockchain Data Reading
- [x] [getBlockNumber()](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2270): Returns the current block number.
- [x] [getGasPrice()](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2271): Returns the current gas price.
- [x] [getBlockByHash(blockHash, includeTransactions)](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2272): Fetches a block by its hash or tag, optionally including transactions.
- [x] [getBlockByNumber(blockParam, includeTransactions)](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2306): Fetches a block by its tag, optionally including transactions.
- [x] [getTransaction(transactionHash)](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2273): Fetches a transaction by its hash.
- [x] [getTransactionReceipt(transactionHash)](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2274): Fetches the receipt of a transaction by its hash.
- [x] [getTransactionCount(address, blockTag)](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2275): Gets the number of transactions sent from an address, optionally at a specific block.
- [x] [getCode(address, blockTag)](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2276): Gets the code at a specific address.
- [x] [getStorageAt(address, position, blockTag)](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2277): Reads a storage slot from a contract.
- [x] [call(transaction, blockTag)](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2278): Simulates a transaction call.
- [x] [estimateGas(transaction)](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2279): Estimates the gas needed to execute a transaction.
- [x] [getBalance(address, blockTag)](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2280): Gets the balance of an address.
- [x] [getLogs(filter)](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2281): Fetches past logs based on a filter object.

### Blockchain Interaction
- [x] [sendTransaction(signedTransaction)](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2282): Sends a signed transaction to the network.

### Misc
- [x] [params validators](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2311): Fetches past logs based on a filter object.
- [x] [websocket JS](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2316): Fetches past logs based on a filter object.
