### ISSUE TITLE
Analyze Hedera EVM Compatibility with the Ethereum Go-client #788

### ISSUE THREAD

**Issue by arianejasuwienas** [hashgraph/hedera-json-rpc-relay#2597]
### Problem

The goal of this issue is to analyze the Hedera EVM compatibility with the Ethereum Go client: [github.com/ethereum/go-ethereum/ethclient](https://pkg.go.dev/github.com/ethereum/go-ethereum/ethclient). We should test every RPC endpoint (Websockets, HTTP) against this specification: [OpenRPC Specification](https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/hashgraph/hedera-json-rpc-relay/main/docs/openrpc.json&uiSchema%5BappBar%5D%5Bui:splitView%5D=false&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false).

### Solution

We have divided the work into a few steps:

- [x] Develop the equivalent of the hardhat-example using the Go client.
- [x] Develop tests that will test the Go client against the Hedera RPC specification.
- [ ] Add the tests to the workflow.
- [x]  Prepare documentation (compatibility report, usage in Hedera, limitations, etc.).

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/pull/2584
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/pull/2586
```
