### ISSUE TITLE
HBar usage metrics need to be enhanced to better track the relay's consumption

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#2643]
### Problem

As usage of the relay increases so the HBar consumed.  The current metrics show the `FileAppendTransaction` consuming a lot of HBar, but the actual costs are not surfaced, and the limiter does not seem to kick in.  Enhancing this code is tricky because it lives in nested private methods, making testing time consuming.  

### Solution

- [x] [Explore the current dashboard panel `Hbar Spent By type`](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2654).  Find a way to surface the costs that are already captured in the metrics and exposed in the prometheus endpoint.  This may require adding new panels.
- [x] [Look at the current HBar rate limiter implementation](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2653).  It seems to only record rate limiting events.  Yet those events are not listed in the prometheus endpoint.  Does that mean the rate limiting is not kicking in when needed, or are the limits just not getting met.  Should the metrics include when the HBar limiter is called, but does not limit the consumption? 
- [x] [Refactor the `createFile` code in a way the facilitates testability](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2655).  Then write unit tests and acceptance tests that can be run in CI as well as used in any future trouble shooting.  At the moment testing this code is time consuming. 
- [x] [Currently the localAcceptance.env](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2671) file uses the 0.0.2 OPERATOR_ID_MAIN which is not the best for testing transaction fees.
- [x] [Using an account other than 0.0.2](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2700) to run the local node causes the deterministic deployment transaction test to fail
- [x] [Add acceptance tests to verify transaction costs and metrics](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2691).  These should verify transaction costs and metrics.  
- [x] [Relay metrics are not exposed](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2694) in the websocket server metrics end point.
- [x] [Use executeAll()](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2693) instead of execute() in FileCreate/Append transactions 
- [x] [HBAR Burned Rate is not captured ](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2707)in executeTransaction() and deleteFile()
- [ ] [Replace getRecord network calls](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2706).
- [ ] [Capture FileInfo queries cost](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2738)
- [x] [Expand HBar Limiter](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2703) coverage.
- [ ] [Redesign](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2739) the HBar rate limiter.
- [x] [Calculate the cost of an eth_sendRawTransaction](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2745) based on callData byte size
- [x] [Reuse executeTransaction()](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2746) for methods in SDKClient and improve logging
- [ ] [Investigate the amount charged](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2748) to the relay operator for every ETHEREUM_TRANSACTION
- [ ] [Break down the costs ](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2757)of the recent FileAppend transactions
- [x] [Expand integration tests for SDK client](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2747)

**Comment by ebadiere** [comment]
Mostly addressed.  Open issues continued in epic #2811
