### ISSUE TITLE
EPIC: Soft Refactor

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-json-rpc-relay#2710]
### Soft Refactor
> ℹ️ This aims to extract from eth.ts all block, receipt and transaction methods and formatters in their respective classes. This will greatly improve readability in eth.ts and will increase cohesion in the relay.

```[tasklist]
### Soft Refactor
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/2676
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/2675
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/2677
```
----
