### ISSUE TITLE
[HBAR Rate Limit Redesign] Redesign of the HBar Rate Limiter

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#2739]
### Problem

The current HBar rate limiter is designed to limit the operator HBar spending over a duration such as a minute, but the relay may get batches of many FileAppend transactions that disproportionally spend the relay's operator balance.  Reducing the remaining balance in the HBar rate limiter can stop the many incoming FileAppend transactions but can also stop other users from simply deploying transactions.  

### Solution

**Redesign the HBar rate limiter**

Consider:

- Rate limiting using the operator's quota for the day.  Query the mirror node for updated operator balance at regular intervals.
- Limit the `FileAppend` per user of IP
-  Define requirements

```[tasklist]
### Tasks
- [x] Implement real-time tracking of HBar spending across different operations and transaction types.
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/2863
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/2850
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/2849
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/2896
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/2933
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/2940
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/2968
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/2970
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/3018
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/3025
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/3055
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/3059
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/3092
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/3096
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/3051
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/3052
```

**Comment by Nana-EC** [comment]
Moving #3109 (unrelated) and #3099 (not required right now) out of EPIC

**Comment by Nana-EC** [comment]
Great job team.
Closing this off
