### ISSUE TITLE
Refactor HBar Rate Limiter.

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#2811]
### Problem

Recently there was an issue with the HBar Rate Limiter.  It was not able to limit the upload of heavy solidity contracts and allowing the relay operator's balance to decrease at an unsustainable level.  Ideas are being collected on how to refactor the HBar Rate Limiter.

### Solution

This epic will track the HBr Rate Limiter refactor work:
- [x] [Replace getRecord with network calls.](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2706)
- [x] [Capture FileInfor queries costs](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2738)
- [x] [Investigate the amount charged to the relay operator for every ETHEREUM_TRANSACTION](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2748)

**Comment by quiet-node** [comment]
New Epic is created https://github.com/hashgraph/hedera-json-rpc-relay/issues/2739
