### ISSUE TITLE
[HBAR Rate Limit Redesign] Create e2e tests for basic spending plan limit

### ISSUE THREAD

**Issue by konstantinabl** [hashgraph/hedera-json-rpc-relay#3065]
```[tasklist]
### Tasks
- [x] Create a test ensuring a user not included in a plan is treated as a BASIC user
- [x] Create a test simulating transactions that accumulate to just below the limit
- [x] Create a test simulating transactions that exceed the limit
- [x] Create a test deploying X amount of contracts for a BASIC user until limited
```
