### ISSUE TITLE
[HBAR Rate Limit Redesign] Create e2e tests for extended spending plan limit

### ISSUE THREAD

**Issue by konstantinabl** [hashgraph/hedera-json-rpc-relay#3066]
```[tasklist]
### Tasks
- [ ] Create a test with EXTENDED user plan with both IP and ETH addresses and accumulate transactions below the limit
- [ ] Create a test with EXTENDED user plan with both IP and ETH addresses and accumulate transactions exceeding the limit
- [ ] Create a test with EXTEDNED user plan deploying X amount of contracts
```
