### ISSUE TITLE
Release 0.61

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-json-rpc-relay#3300]
### Problem

The Hedera JSON-RPC Relay repository contains new features that have not yet been included in an official release version.

### Solution

Publish a new release to incorporate all the recently added features.

### Alternatives

_No response._
```[tasklist]
### Tasks
- [x] Clean up milestone, ticket, PR boards
- [x] Cut 0.61.0-rc1
- [x] Generate new Bump SNAPSHOT PR
- [x] Deploy RC1 (previewnet, testnet)
- [x] Release Test - Newman Test
- [x] Release Test - DApp Test
- [x] Release Test - Perf Test
- [x] Release Test - Acceptance Test
- [x] Cut 0.61.0 GA
- [x] Deploy 0.61.0 GA (previewnet, testnet, mainnet)
```

**Comment by quiet-node** [comment]
Version 0.61.0 has successfully been released. Detail can be found in https://github.com/hashgraph/hedera-json-rpc-relay/releases/tag/v0.61.0
