### ISSUE TITLE
[EPIC] Custom API Support for Explorers

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#3314]
### Problem

Many web3 products rely on custom APIs on the EVM block explorer (e.g. Etherscan, BlockScouts, etc), however, our MNE is split up as a clients and a backend that's HAPI focused.
Therefore there's no EVM focused REST API's to support some of these expected APIs 

Etherscan required APIs endpoints:
1. https://docs.etherscan.io/api-endpoints/blocks#get-block-and-uncle-rewards-by-blockno (module=block, action=getblockreward)
2. https://docs.etherscan.io/api-endpoints/accounts#get-a-list-of-erc721-token-transfer-events-by-address (module=account, action=tokennfttx)
3. https://docs.etherscan.io/api-endpoints/accounts#get-a-list-of-erc1155-token-transfer-events-by-address (module=account, action=token1155tx)

Blockscout RPC API endpoints:
1. https://docs.blockscout.com/devs/apis/rpc/block#get-block-reward-by-block-number (module=block, action=getblockreward)
2. https://docs.blockscout.com/devs/apis/rpc/account#get-token-transfer-events-by-address (module=account, action=tokentx)
3. https://docs.blockscout.com/devs/apis/rpc/account#get-list-of-tokens-owned-by-address (module=account, action=tokenlist)

### Solution

Add custom REST API support to the relay which will allow the MNE to pass through queries and responses to satisfy community expectations on these APIs

```[tasklist]
### Block Explorer Supporting Custom API Tasks
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/3324
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/3340
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/3372
```

**Comment by konstantinabl** [comment]
The research was done and we have chosen an approach
