### ISSUE TITLE
Release 0.62

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-json-rpc-relay#3325]
### Problem

The Hedera JSON-RPC Relay repository contains new features that have not yet been included in an official release version.

### Solution

Publish a new release to incorporate all the recently added features.

### Alternatives

_No response._
```[tasklist]
### Tasks
- [x] Clean up milestone, ticket, PR boards
- [x] Cut 0.62.0-rc1
- [x] Generate new Bump SNAPSHOT PR
- [x] Deploy RC1 (previewnet, testnet)
- [x] Release Test - Newman Test
- [x] Release Test - DApp Test
- [x] Release Test - Perf Test
- [x] Release Test - Acceptance Test
- [x] Cut 0.62.0 GA
- [ ] Deploy 0.61.0 GA (previewnet, testnet, mainnet)
```
