### ISSUE TITLE
Relay <> The Graph Integration

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-json-rpc-relay#414]
### Overview
The idea behind this item is to enable developers to run Graph nodes against the relay endpoint and utilise subgraphs for smart contract event indexing

### Features

**General**

- [x] Being able to catch & handle events emitted from `EthereumTransactions` - Generally works, but is blocked by other issues https://github.com/hashgraph/hedera-json-rpc-relay/issues/417, https://github.com/hashgraph/hedera-json-rpc-relay/pull/432 and https://github.com/hashgraph/hedera-mirror-node/issues/4175 which affect the indexing of the blocks
- [x] Being able to catch & handle events emitted from `ContractCall` & `ContractCreate` - not working because of https://github.com/hashgraph/hedera-mirror-node/issues/4175
- [x] Being able to specify the start time from which the graph syncs - This uses `startBlock` from the `subgraph.yaml`. From the limited success indexing the relay it looks as it's working, but it requires that all blocks down to the startBlock has been consumed, which currently can't be well tested.
- [ ] Being able to define `call handlers` and process them - Requires trace api implementation https://openethereum.github.io/JSONRPC-trace-module - **_not supported_**.
- [x] Being able to define `block handlers` without filters and process them - **_supported_**
- [ ] Being able to define `block handlers` with filters and process them - Requires trace api implementation https://openethereum.github.io/JSONRPC-trace-module - **_not supported_**.
- [x] Being able to execute `contract calls` during subgraph event processing (contract calls) - https://github.com/hashgraph/hedera-json-rpc-relay/issues/437

**Hedera specific**

- [ ] Being able to capture HTS token transfers through HTS precompile -> Should be working. Must be tested (cc @dimitrovmaksim )
- [ ] Being able to capture HTS token transfers through HAPI ->  HTS token transfers from HAPI are not emitting events equivalent to ERC20 transfer. - https://github.com/hashgraph/hedera-mirror-node/issues/4337, https://github.com/hashgraph/hedera-mirror-node/issues/4738

**Comment by dimitrovmaksim** [comment]
```sh
Trying again after eth_getBlockByHash RPC call for block hash
0x2334e29a448fe8be0c13b0df99d0e0cef5f929e4102f595f47dae6257dfd9dc6 failed (attempt #1) with result
Err(Decoder error: Error("invalid type: null, expected a (both 0x-prefixed or not) hex string with length between (0; 64]",
line: 0, column: 0)), provider: localhost-rpc-0, component: BlockIngestor
```

This happens with blocks that have transactions. The the required null property by the graph node in this case is `nonce`, but generally there are more missing properties, probably related to this Issue https://github.com/hashgraph/hedera-json-rpc-relay/issues/417

**Comment by dimitrovmaksim** [comment]
Graph node error: 
```
Trying again after block polling failed: Block data unavailable, block was likely uncled (block hash = 0x25dc6dd3ccb9484dc016163687462ac852c181624e6c8fb5e755acb283d91026), provider: hedera-rpc-0, component: BlockIngestor
```

Probable cause - mirror node timeout:
```
Relay: 
 err: {
      "type": "Error",
      "message": "timeout of 10000ms exceeded",
      "stack":
          Error: timeout of 10000ms exceeded
              at MirrorNodeClient.handleError (.../hedera-json-rpc-relay/packages/relay/dist/lib/clients/mirrorNodeClient.js:107:27)
              at MirrorNodeClient.<anonymous> (.../hedera-json-rpc-relay/packages/relay/dist/lib/clients/mirrorNodeClient.js:95:22)
              at Generator.throw (<anonymous>)
              at rejected (.../hedera-json-rpc-relay/packages/relay/dist/lib/clients/mirrorNodeClient.js:25:65)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
    }
```

**Comment by dimitrovmaksim** [comment]
Graph node error - `Could not find thx receipt`

Probable cause:
`eth_getTransactionReceipt` method is mapped to `getContractResult(hash)(/api/v1/contracts/results/{TransactionIdOrHash}` but this endpoint returns results [only?] for `CONTRACTCALL` type transactions
https://testnet.mirrornode.hedera.com/api/v1/contracts/results/0x4e8e53974dee424c3ebff7e0a6ff24824f64eced01947dca97d9ea0465214e09

Not sure if this an issue for the indexing process

**Comment by dimitrovmaksim** [comment]
Blocks that return empty contractResult have `0` as timestamp. 
`timestamp` is seto to 0 here https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/eth.ts#L935 and is only updated if contractResults is not empty https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/eth.ts#L942-L945, otherwise it remains `0` and is set as `0 `to the Block response https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/eth.ts#L976

**Comment by dimitrovmaksim** [comment]
Managed to get the graph node to index an event after hardcoding some values in the relay 
```Aug 08 12:41:33.100 INFO Done processing trigger, gas_used: 164806718, data_source: EmitEvent, handler: handleTestEvent, total_ms: 14, transaction: 0xfd71…3c13, address: 0x0000…fa89, signature: TestEvent(uint256), sgd: 1, subgraph_id: QmdNoQ1s7hBxZkdHfdUu68HCqd6DX3C9jWUj8XXj8BYDqA, component: SubgraphInstanceManager```

**Comment by Daniel-K-Ivanov** [comment]
> It seems this one actually breaks the processing of the triggers
> 
> Graph node error - `Aug 04 15:00:22.191 INFO Trying again after block polling failed: Receipt for tx 0x67a252b497f13e3fcd263016f33fde5969de0f4ed6bca1d49bc4665336566072 unavailable, block was likely uncled (block hash = 0x10aefdc2106412ed4cc688543040d4e7152d28d3d9a04be0c85267736b6e391f), provider: testnet-rpc-0, component: BlockIngestor`
> 
> Probable cause: [#371 (comment)](https://github.com/hashgraph/hedera-json-rpc-relay/issues/371#issuecomment-1205523777)

Actually, this is due to https://github.com/hashgraph/hedera-mirror-node/issues/4175

**Comment by Daniel-K-Ivanov** [comment]
> Blocks that return empty contractResult have `0` as timestamp. `timestamp` is seto to 0 here https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/eth.ts#L935 and is only updated if contractResults is not empty https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/eth.ts#L942-L945, otherwise it remains `0` and is set as `0 `to the Block response https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/eth.ts#L976

Will be fixed by #432

**Comment by dimitrovmaksim** [comment]
Trying to make contract calls from an eventHandler results in (tried agains all test nodes). Also replicated directly through the SDK, both `ContractCallQuery#getCost()` and `ContractCallQuery#execute()` yield the same error.
```
[2022-08-09 08:31:01.777 +0000] ERROR (...): Failed to successfully submit contractCallQuery
    err: {
      "type": "Error",
      "message": "max attempts of 10 was reached for request with last error being: BUSY",
      "stack":
          Error: max attempts of 10 was reached for request with last error being: BUSY
              at CostQuery.execute (/Users/.../Projects/hedera/hedera-json-rpc-relay/node_modules/@hashgraph/sdk/lib/Executable.cjs:715:11)
    }
```
Maybe not related, but the relay complains that `ContractId.fromSolidityAddress()` is deprecated and has to use `ContractId.fromEvmAddress()`, but it seem `fromEvmAddress()` does not produce a correct ContractId
Both `ContractId.fromEvmAddress(0, 0, "0x0000000000000000000000000000000002d9fa89")` and `ContractId.fromEvmAddress(0, 0, "0000000000000000000000000000000002d9fa89")` will return
```
ContractId {
  shard: Long { low: 0, high: 0, unsigned: false },
  realm: Long { low: 0, high: 0, unsigned: false },
  num: Long { low: 0, high: 0, unsigned: false },
  evmAddress: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 02 d9 fa 89>,
  _checksum: null
}```

**Comment by dimitrovmaksim** [comment]
> Being able to capture HTS token transfers through HTS precompile -> Should be working. Must be tested (cc @dimitrovmaksim )

1. Deploy BaseHTS contract
2. Create token via `createFungibleTokenPublic`
3. Associate token to owner and receiver via BaseHTS `associateTokenPublic`
4. Transfer token via mock ERC20 contract's `transfer(to, amount)`

Event is emitted and indexed.

Note: Using hedera-local-node `main` branch results in the wrong event contract/token, `from` and `to` addresses being emitted, because the it uses older docker images. Later version have this fixed. Maybe create a `dev` branch in the hedera-local-node where the docker images are updated or uses the latest images, so it easier to test.

**Comment by Kalina-Todorova** [comment]
Related issues:
https://github.com/hashgraph/hedera-json-rpc-relay/issues/644
