### ISSUE TITLE
Automate git branch process for main and release branch

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#903]
### Problem

The current release process sees the following manual steps
1. A PR to bump the SNAPSHOT version in `main`
2. Creation of a new `release/<major>.<minor>` branch and a PR to bump the version to an `alpha-1`/`rc-1` version

This results in us continuously questioning if we got every file in the bump PRs

### Solution

- [x] automate the git branch creation process on an rc1 or alpha1
- [x] automate the find and replace of sem ver values x.y.z with considerations for snapshot and rc or alphas
- [x] expose automation for bump version in a git hub action
- [x] expose git tag and draft release automation in a github action

Resources
- [Mirror Node Automated Release Process](https://github.com/hashgraph/hedera-mirror-node/blob/main/.github/workflows/release-automation.yml)
- https://cli.github.com/manual/gh_release

**Comment by AlfredoG87** [comment]
@Nana-EC, I think this is completed, most of the items done by you 😅 
Will close ticket, but if you think otherwise feel free to re-open it.
